#!/usr/bin/env php
<?php
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

require 'vendor/autoload.php';

$app = new Application('SSH Watcher');

$app->register('start')
    ->setDescription('Start the watcher daemon.')
    ->setCode(function (InputInterface $input, OutputInterface $output) {
        $output->writeln('test');
    });

$app->run();