#!/usr/bin/env php
<?php
use Jaggy\Watcher\StartDaemonCommand;
use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$app = new Application('SSH Watcher');

$app->add(new StartDaemonCommand());
$app->run();